app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from . import views

page_urlpatterns = [
    path('', views.PageIndex.as_view(), name='pages_index'),
    path('<int:pk>/', views.PageDetail.as_view(), name='page_detail'),
    path('types/<type>/', views.PageCreate.as_view(), name='page_create'),
]

user_urlpatterns = [
    path('<int:user_id>/', views.UserDetail.as_view(), name='user_detail'),
    path('login/', auth_views.LoginView.as_view(
        template_name="users/user_login.html", extra_context={'next':'/'}), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.UserRegister.as_view(), name='register')
]

urlpatterns = [
    path('', views.Home.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path('pages/', include(page_urlpatterns)),
    path('users/', include(user_urlpatterns))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crimewiki/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


from . import views


urlpatterns = [
    path('', views.Home.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path('pages/', include('pages.urls')),
    path('users/', include('users.urls')),
    path('comments/', include('comments.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import include, path
from pages import views

app_name = 'pages'
urlpatterns = [
    path('', views.PageIndex.as_view(), name='pages_index'),
    path('<int:pk>/', views.PageDetail.as_view(), name='page_detail'),
    path('types/<type>/', views.PageCreate.as_view(), name='page_create'),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include, path
from users import views
app_name = 'users'
urlpatterns = [
    path('', views.UserList.as_view(), name='user_list'),
    path('<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('login/', auth_views.LoginView.as_view(
        template_name="user_login.html", extra_context={'next':'/'}), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.UserRegister.as_view(), name='register')
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.views.generic import ListView, CreateView, DetailView
from django.http import HttpResponseRedirect
# Create your views here.


class UserList(ListView):
    template_name = 'users/user_list.html'
    model = User


class UserRegister(CreateView):
    form_class = UserCreationForm
    template_name = 'user_form.html'
    success_url = '/'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.groups.add('RegularUsers')
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class UserDetail(DetailView):
    model = User
    template_name = 'users/user_detail.html'

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}Crime Wiki{% endblock %}</title>
  {% load static %}
  {% block stylesheets %} <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% endblock stylesheets %}
</head>
<body>
  <nav>
    {% block navigation %}
      <ul>
        <li>
          <a href="{% url 'home' %}">Home</a>
        </li>
        <li>
          <a href="{% url 'pages:pages_index' %}">Cases</a>
        </li>
        <li>
          <a href="{% url 'users:user_list' %}">Users</a>
        </li>
        <li>
          {% block user %}
            {% include "navbar_widget.html" %}
          {% endblock user %}
        </li>
      </ul>

    {% endblock %}
  </nav>
  {% block content %}{% endblock %}
</body>
{% block root_scripts %}
  {% load static %}
  <script src="{% static '/js/core.js' %}" charset="utf-8"></script>
{% endblock root_scripts %}

{% block scripts %}{% endblock %}
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>Pages</h1>
{% if object_list %}
    <ul>
    {% for page in object_list %}
        <li><a href="{% url 'pages:page_detail' page.id %}">{{ page }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No pages are available.</p>
{% endif %}
{% endblock %}

templates/navbar_widget.html
{% if user.is_authenticated %}
  <span><a href="{% url 'users:user_detail' user.id %}">{{ user.get_username }}</a> - <a href="{% url 'users:logout' %}">Logout</a></span>
{% else %}
  <span><a href="{% url 'users:login' %}">Login</a> - <a href="{% url 'register' %}">Register</a></span>
{% endif %}

templates/user_detail.html
{% extends 'base.html' %}

{% block content %}

{{ user_detail.get_username }}
<h1>Cases</h1>
{% if case_list %}
    <ul>
    {% for case in case_list %}
        <li><a href="{% url 'cases:detail' case.id %}">{{ case }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No cases are available.</p>
{% endif %}
{% endblock content %}

templates/user_form.html
{% extends 'base.html' %}

{% block content %}

<form action="{% url 'register' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
{% endblock content %}

templates/user_login.html
{% extends "base.html" %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>

{# Assumes you setup the password_reset view in your URLconf #}
{# <p><a href="{% url 'password_reset' %}">Lost password?</a></p> #}

{% endblock %}